/*
 * TradingDialog.java
 *
 * Created on March 7, 2007, 1:19 PM
 */

package nade_project;

/**
 *This dialog allows the user to negotiate and trade resources/profit with other clients.
 * @author  Default
 */
public class BankingDialog extends javax.swing.JFrame
{

    /**Nade client class*/
    NadeClient nadeClient;

    /** Creates new form TradingDialog */
    public BankingDialog( NadeClient _nadeClient )
    {
        initComponents();
        nadeClient = _nadeClient;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabelRecipient = new javax.swing.JLabel();
        jComboBoxRecipient = new javax.swing.JComboBox();
        jLabelResourcesToGive = new javax.swing.JLabel();
        jLabelResources = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jLabelMoneyToGive = new javax.swing.JLabel();
        jTextFieldMoneyToGive = new javax.swing.JTextField();
        jTextFieldMoneyAvailable = new javax.swing.JTextField();
        jTextFieldResourcesAvailable = new javax.swing.JTextField();
        jTextFieldResourcesToGive = new javax.swing.JTextField();
        jButtonGiveMoney = new javax.swing.JButton();
        jButtonGiveResources = new javax.swing.JButton();
        jLabelBanking = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxGroupToAsk = new javax.swing.JComboBox();
        jLabelGroupToAsk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMoneyToAskFor = new javax.swing.JLabel();
        jTextFieldResourcesToAskFor = new javax.swing.JTextField();
        jTextFieldMoneyToAskFor = new javax.swing.JTextField();
        jButtonAskForMoney = new javax.swing.JButton();
        jButtonAskForResources = new javax.swing.JButton();
        jLabelNegotiating = new javax.swing.JLabel();
        jLabelNegotiateResourcesToGive = new javax.swing.JLabel();
        jLabelNegotiateMoneyToGive = new javax.swing.JLabel();
        jTextFieldNegotiateGiveResources = new javax.swing.JTextField();
        jTextFieldNegotiateGiveMoney = new javax.swing.JTextField();
        jButtonNegotiateGiveResources = new javax.swing.JButton();
        jButtonNegotiateGiveMoney = new javax.swing.JButton();

        setTitle("Banking and Negotiating Dialog");
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelRecipient.setText("Group to give");

        jLabelResourcesToGive.setText("Resources to Give");

        jLabelResources.setText("Resources Available");

        jLabelMoney.setText("Money Available");

        jLabelMoneyToGive.setText("Money to Give");

        jTextFieldMoneyToGive.setDocument(new IntegerDocument());
        jTextFieldMoneyToGive.setText("0");

        jTextFieldMoneyAvailable.setDocument(new IntegerDocument());
        jTextFieldMoneyAvailable.setEditable(false);
        jTextFieldMoneyAvailable.setText("0");

        jTextFieldResourcesAvailable.setDocument(new IntegerDocument());
        jTextFieldResourcesAvailable.setEditable(false);
        jTextFieldResourcesAvailable.setText("0");

        jTextFieldResourcesToGive.setDocument(new IntegerDocument());
        jTextFieldResourcesToGive.setText("0");

        jButtonGiveMoney.setText("Give Money");
        jButtonGiveMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiveMoneyActionPerformed(evt);
            }
        });

        jButtonGiveResources.setText("Give Resources");
        jButtonGiveResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiveResourcesActionPerformed(evt);
            }
        });

        jLabelBanking.setText("Banking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBanking)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRecipient)
                            .addComponent(jLabelResourcesToGive)
                            .addComponent(jLabelMoney)
                            .addComponent(jLabelResources)
                            .addComponent(jLabelMoneyToGive))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldResourcesAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMoneyAvailable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldResourcesToGive, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGiveResources))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldMoneyToGive, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGiveMoney))
                            .addComponent(jComboBoxRecipient, 0, 220, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBanking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRecipient)
                    .addComponent(jComboBoxRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResources)
                    .addComponent(jTextFieldResourcesAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResourcesToGive)
                    .addComponent(jButtonGiveResources)
                    .addComponent(jTextFieldResourcesToGive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMoney)
                    .addComponent(jTextFieldMoneyAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGiveMoney)
                            .addComponent(jTextFieldMoneyToGive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelMoneyToGive))
                .addGap(51, 51, 51))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelGroupToAsk.setText("Group To Ask");

        jLabel1.setText("Resources To Ask For");

        jLabelMoneyToAskFor.setText("Money To Ask For");

        jTextFieldResourcesToAskFor.setDocument(new IntegerDocument());
        jTextFieldResourcesToAskFor.setText("0");

        jTextFieldMoneyToAskFor.setDocument(new IntegerDocument());
        jTextFieldMoneyToAskFor.setText("0");

        jButtonAskForMoney.setText("Ask For Money");
        jButtonAskForMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskForMoneyActionPerformed(evt);
            }
        });

        jButtonAskForResources.setText("Ask For Resources");
        jButtonAskForResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskForResourcesActionPerformed(evt);
            }
        });

        jLabelNegotiating.setText("Negotiating");

        jLabelNegotiateResourcesToGive.setText("Resources to Give");

        jLabelNegotiateMoneyToGive.setText("Money to Give");

        jTextFieldNegotiateGiveResources.setDocument(new IntegerDocument());
        jTextFieldNegotiateGiveResources.setText("0");

        jTextFieldNegotiateGiveMoney.setDocument(new IntegerDocument());
        jTextFieldNegotiateGiveMoney.setText("0");

        jButtonNegotiateGiveResources.setText("Give Resources");
        jButtonNegotiateGiveResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegotiateGiveResourcesActionPerformed(evt);
            }
        });

        jButtonNegotiateGiveMoney.setText("Give Money");
        jButtonNegotiateGiveMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegotiateGiveMoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNegotiating)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGroupToAsk)
                            .addComponent(jLabel1)
                            .addComponent(jLabelMoneyToAskFor)
                            .addComponent(jLabelNegotiateResourcesToGive)
                            .addComponent(jLabelNegotiateMoneyToGive))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxGroupToAsk, 0, 226, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNegotiateGiveMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNegotiateGiveResources, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMoneyToAskFor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jTextFieldResourcesToAskFor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAskForResources, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAskForMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNegotiateGiveMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNegotiateGiveResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNegotiating)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroupToAsk)
                    .addComponent(jComboBoxGroupToAsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResourcesToAskFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAskForResources))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoneyToAskFor)
                    .addComponent(jTextFieldMoneyToAskFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAskForMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNegotiateResourcesToGive)
                    .addComponent(jTextFieldNegotiateGiveResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNegotiateGiveResources))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNegotiateMoneyToGive)
                    .addComponent(jTextFieldNegotiateGiveMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNegotiateGiveMoney))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNegotiateGiveMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegotiateGiveMoneyActionPerformed
       if( nadeClient != null )
       {
          double amount = Double.valueOf( jTextFieldNegotiateGiveMoney.getText() );
          nadeClient.GiveNegotiateResources( (int)amount );
       }
    }//GEN-LAST:event_jButtonNegotiateGiveMoneyActionPerformed

    private void jButtonNegotiateGiveResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegotiateGiveResourcesActionPerformed
       if( nadeClient != null )
       {
          double amount = Double.valueOf( jTextFieldNegotiateGiveResources.getText() );
          nadeClient.GiveNegotiateResources( (int)amount );
       }
    }//GEN-LAST:event_jButtonNegotiateGiveResourcesActionPerformed

    private void jButtonAskForMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskForMoneyActionPerformed
       if( nadeClient != null )
       {
           nadeClient.AskMoney();
       }
    }//GEN-LAST:event_jButtonAskForMoneyActionPerformed

    private void jButtonAskForResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskForResourcesActionPerformed
       if( nadeClient != null )
       {
           nadeClient.AskResources();
       }
    }//GEN-LAST:event_jButtonAskForResourcesActionPerformed

    private void jButtonGiveResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiveResourcesActionPerformed
       if( nadeClient != null )
       {
           nadeClient.GiveResources();
       }
    }//GEN-LAST:event_jButtonGiveResourcesActionPerformed

    private void jButtonGiveMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiveMoneyActionPerformed
       if( nadeClient != null )
       {
           nadeClient.GiveMoney();
       }
    }//GEN-LAST:event_jButtonGiveMoneyActionPerformed
    
    javax.swing.JTextField getjTextFieldMoneyToGive()
    {
        return jTextFieldMoneyToGive;
    }
    javax.swing.JTextField getjTextFieldResourcesToGive()
    {
        return jTextFieldResourcesToGive;
    }
    javax.swing.JButton getjButtonGiveResources()
    {
        return jButtonGiveResources;
    }
    javax.swing.JButton getjButtonGiveMoney()
    {
        return jButtonGiveMoney;
    }
    javax.swing.JComboBox getjComboBoxRecipient()
    {
        return jComboBoxRecipient;
    }
    javax.swing.JComboBox getjComboBoxGroupToAsk()
    {
        return jComboBoxGroupToAsk;
    }
    javax.swing.JTextField getjTextFieldResourcesAvailable()
    {
        return jTextFieldResourcesAvailable;
    }
    javax.swing.JTextField getjTextFieldMoneyAvailable()
    {
        return jTextFieldMoneyAvailable;
    }
    javax.swing.JTextField getjTextFieldMoneyToAskFor()
    {
        return jTextFieldMoneyToAskFor;
    }
    javax.swing.JTextField getjTextFieldResourcesToAskFor()
    {
        return jTextFieldMoneyToAskFor;
    }
    /**@return jTextFieldNegotiateGiveResources*/
    javax.swing.JTextField getjTextFieldNegotiateGiveResources()
    {
        return jTextFieldNegotiateGiveResources;
    }
    /**@return jTextFieldNegotiateGiveMoney*/
    javax.swing.JTextField getjTextFieldNegotiateGiveMoney()
    {
        return jTextFieldNegotiateGiveMoney;
    }


        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAskForMoney;
    private javax.swing.JButton jButtonAskForResources;
    private javax.swing.JButton jButtonGiveMoney;
    private javax.swing.JButton jButtonGiveResources;
    private javax.swing.JButton jButtonNegotiateGiveMoney;
    private javax.swing.JButton jButtonNegotiateGiveResources;
    private javax.swing.JComboBox jComboBoxGroupToAsk;
    private javax.swing.JComboBox jComboBoxRecipient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBanking;
    private javax.swing.JLabel jLabelGroupToAsk;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelMoneyToAskFor;
    private javax.swing.JLabel jLabelMoneyToGive;
    private javax.swing.JLabel jLabelNegotiateMoneyToGive;
    private javax.swing.JLabel jLabelNegotiateResourcesToGive;
    private javax.swing.JLabel jLabelNegotiating;
    private javax.swing.JLabel jLabelRecipient;
    private javax.swing.JLabel jLabelResources;
    private javax.swing.JLabel jLabelResourcesToGive;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMoneyAvailable;
    private javax.swing.JTextField jTextFieldMoneyToAskFor;
    private javax.swing.JTextField jTextFieldMoneyToGive;
    private javax.swing.JTextField jTextFieldNegotiateGiveMoney;
    private javax.swing.JTextField jTextFieldNegotiateGiveResources;
    private javax.swing.JTextField jTextFieldResourcesAvailable;
    private javax.swing.JTextField jTextFieldResourcesToAskFor;
    private javax.swing.JTextField jTextFieldResourcesToGive;
    // End of variables declaration//GEN-END:variables
    
}
