/*
 * ContractInfoDialog.java
 *
 * Created on March 7, 2007, 2:34 AM
 */

package nade_project;

/**
 *This dialog displays information about the current contract.
 * @author  Default
 */
public class ContractInfoDialog extends javax.swing.JFrame {
    
    /** Creates new form ContractInfoDialog */
    public ContractInfoDialog()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    /**Calculates the value of the contract maxprofit/minresources
     *and stores it in jTextFieldContractValue.
     *@return maxprofit/minresources
     */
    public double SetContractValue()
    {
        double    maxprofit = Double.valueOf( jTextFieldContractMaximumProfit.getText() );
        double minresources = Double.valueOf( jTextFieldContractMinimumResourses.getText());
        double        value = (int)(maxprofit/minresources);
        jTextFieldContractValue.setText( String.valueOf( value ) );
        return value;
    }

    /**Calculates the value of the resource cost*min resources
     *and stores it in jTextFieldTradeProfit.
     *How much money you woulg gain if you sold the resources instead of bid on a contract.
     *@return resourcecost*minresources
     */
    public double SetTradeProfit()
    {
        double resourcecost = Double.valueOf( jTextFieldContractCostPerUnit.getText()      );
        double minresources = Double.valueOf( jTextFieldContractMinimumResourses.getText() );
        double       profit = resourcecost*minresources;
        jTextFieldTradeProfit.setText( String.valueOf( profit ) );
        return profit;
    }


    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelContract = new javax.swing.JPanel();
        jLabelContractName = new javax.swing.JLabel();
        jTextFieldContractName = new javax.swing.JTextField();
        jTextFieldContractMaximumTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldContractMinimumResourses = new javax.swing.JTextField();
        jLabelContractMinimumResourses = new javax.swing.JLabel();
        jLabelContractMaximumProfit = new javax.swing.JLabel();
        jTextFieldContractMaximumProfit = new javax.swing.JTextField();
        jLabelContractCostPerUnit = new javax.swing.JLabel();
        jTextFieldContractCostPerUnit = new javax.swing.JTextField();
        jLabelContractCostPerHealthUnit = new javax.swing.JLabel();
        jTextFieldContractCostperHealthUnit = new javax.swing.JTextField();
        jLabelContractBribeResourceAmount = new javax.swing.JLabel();
        jTextFieldContractBribeResourceAmount = new javax.swing.JTextField();
        jLabelContractEthicsRate = new javax.swing.JLabel();
        jTextFieldContractEthicsRate = new javax.swing.JTextField();
        jLabelContractResourceUnits = new javax.swing.JLabel();
        jTextFieldContractResourceUnits = new javax.swing.JTextField();
        jLabelContractProfitUnits = new javax.swing.JLabel();
        jTextFieldContractProfitUnits = new javax.swing.JTextField();
        jLabelContractNumber = new javax.swing.JLabel();
        jTextFieldContractNumber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldContractValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelTradeProfit = new javax.swing.JLabel();
        jTextFieldTradeProfit = new javax.swing.JTextField();

        setTitle("Contract Information");
        jPanelContract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelContractName.setText("Name");

        jTextFieldContractName.setEditable(false);
        jTextFieldContractName.setText("Contract");
        jTextFieldContractName.setToolTipText("Contract Name");

        jTextFieldContractMaximumTime.setEditable(false);
        jTextFieldContractMaximumTime.setText("0");

        jLabel2.setText("Maximum Time");

        jTextFieldContractMinimumResourses.setEditable(false);
        jTextFieldContractMinimumResourses.setText("0");

        jLabelContractMinimumResourses.setText("Minimum Resourses");

        jLabelContractMaximumProfit.setText("Maximum Profit");

        jTextFieldContractMaximumProfit.setEditable(false);
        jTextFieldContractMaximumProfit.setText("0");

        jLabelContractCostPerUnit.setText("Cost Per Unit");

        jTextFieldContractCostPerUnit.setEditable(false);
        jTextFieldContractCostPerUnit.setText("0");

        jLabelContractCostPerHealthUnit.setText("Cost Per Health Unit");

        jTextFieldContractCostperHealthUnit.setEditable(false);
        jTextFieldContractCostperHealthUnit.setText("0");

        jLabelContractBribeResourceAmount.setText("Bribe Resource Amount");

        jTextFieldContractBribeResourceAmount.setEditable(false);
        jTextFieldContractBribeResourceAmount.setText("0");

        jLabelContractEthicsRate.setText("Ethics Rate");

        jTextFieldContractEthicsRate.setEditable(false);
        jTextFieldContractEthicsRate.setText("0");

        jLabelContractResourceUnits.setText("Resource Units Added");

        jTextFieldContractResourceUnits.setEditable(false);
        jTextFieldContractResourceUnits.setText("0");
        jTextFieldContractResourceUnits.setToolTipText("Resources injected into NADE.");

        jLabelContractProfitUnits.setText("Profit Units Added");

        jTextFieldContractProfitUnits.setEditable(false);
        jTextFieldContractProfitUnits.setText("0");
        jTextFieldContractProfitUnits.setToolTipText("Money injected into NADE.");

        jLabelContractNumber.setText("Contract Number");

        jTextFieldContractNumber.setDocument(new DoubleDocument());
        jTextFieldContractNumber.setEditable(false);
        jTextFieldContractNumber.setText("0");

        javax.swing.GroupLayout jPanelContractLayout = new javax.swing.GroupLayout(jPanelContract);
        jPanelContract.setLayout(jPanelContractLayout);
        jPanelContractLayout.setHorizontalGroup(
            jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContractLayout.createSequentialGroup()
                        .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContractBribeResourceAmount)
                            .addComponent(jLabelContractCostPerHealthUnit)
                            .addComponent(jLabelContractName)
                            .addComponent(jLabel2)
                            .addComponent(jLabelContractMinimumResourses)
                            .addComponent(jLabelContractMaximumProfit)
                            .addComponent(jLabelContractCostPerUnit)
                            .addComponent(jLabelContractEthicsRate)
                            .addComponent(jLabelContractResourceUnits)
                            .addComponent(jLabelContractProfitUnits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContractLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContractMinimumResourses, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContractMaximumTime, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContractName, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContractMaximumProfit, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContractNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                            .addComponent(jTextFieldContractCostPerUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractCostperHealthUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractBribeResourceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractEthicsRate, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractResourceUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractProfitUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addComponent(jLabelContractNumber))
                .addContainerGap())
        );
        jPanelContractLayout.setVerticalGroup(
            jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractNumber)
                    .addComponent(jTextFieldContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractName)
                    .addComponent(jTextFieldContractName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContractMaximumTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContractMinimumResourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContractMinimumResourses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractMaximumProfit)
                    .addComponent(jTextFieldContractMaximumProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractCostPerUnit)
                    .addComponent(jTextFieldContractCostPerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractCostPerHealthUnit)
                    .addComponent(jTextFieldContractCostperHealthUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractBribeResourceAmount)
                    .addComponent(jTextFieldContractBribeResourceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractEthicsRate)
                    .addComponent(jTextFieldContractEthicsRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractResourceUnits)
                    .addComponent(jTextFieldContractResourceUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractProfitUnits)
                    .addComponent(jTextFieldContractProfitUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldContractValue.setDocument(new DoubleDocument());
        jTextFieldContractValue.setEditable(false);
        jTextFieldContractValue.setText("0");
        jTextFieldContractValue.setToolTipText("max profit/min resources");

        jLabel1.setText("Contract Value");

        jLabelTradeProfit.setText("Trade Profit");

        jTextFieldTradeProfit.setDocument(new DoubleDocument());
        jTextFieldTradeProfit.setEditable(false);
        jTextFieldTradeProfit.setText("0");
        jTextFieldTradeProfit.setToolTipText("How much money you woulg gain if you sold the resources instead of bid on a contract.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTradeProfit)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldTradeProfit, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldContractValue, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContractValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTradeProfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTradeProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContract, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**@return jTextFieldTradeProfit*/
    javax.swing.JTextField getjTextFieldTradeProfit()
    {
        return jTextFieldTradeProfit;
    }
    javax.swing.JTextField getjTextFieldContractName()
    {
        return jTextFieldContractName;
    }
    javax.swing.JTextField getjTextFieldContractMaximumTime()
    {
        return jTextFieldContractMaximumTime;
    }
    javax.swing.JTextField getjTextFieldContractMinimumResourses()
    {
        return jTextFieldContractMinimumResourses;
    }
    javax.swing.JTextField getjTextFieldContractMaximumProfit()
    {
        return jTextFieldContractMaximumProfit;
    }
    javax.swing.JTextField getjTextFieldContractCostPerUnit()
    {
        return jTextFieldContractCostPerUnit;
    }
    javax.swing.JTextField getjTextFieldContractCostperHealthUnit()
    {
        return jTextFieldContractCostperHealthUnit;
    }
    javax.swing.JTextField getjTextFieldContractBribeResourceAmount()
    {
        return jTextFieldContractBribeResourceAmount;
    }
    javax.swing.JTextField getjTextFieldContractEthicsRate()
    {
        return jTextFieldContractEthicsRate;
    }
    javax.swing.JTextField getjTextFieldContractResourceUnits()
    {
        return jTextFieldContractResourceUnits;
    }
    javax.swing.JTextField getjTextFieldContractProfitUnits()
    {
        return jTextFieldContractProfitUnits;
    }
    /**@returns jTextFieldContractValue*/
    javax.swing.JTextField getjTextFieldContractValue()
    {
        return jTextFieldContractValue;
    }
    /**@returns jTextFieldContractNumber*/
    javax.swing.JTextField getjTextFieldContractNumber()
    {
        return jTextFieldContractNumber;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContractBribeResourceAmount;
    private javax.swing.JLabel jLabelContractCostPerHealthUnit;
    private javax.swing.JLabel jLabelContractCostPerUnit;
    private javax.swing.JLabel jLabelContractEthicsRate;
    private javax.swing.JLabel jLabelContractMaximumProfit;
    private javax.swing.JLabel jLabelContractMinimumResourses;
    private javax.swing.JLabel jLabelContractName;
    private javax.swing.JLabel jLabelContractNumber;
    private javax.swing.JLabel jLabelContractProfitUnits;
    private javax.swing.JLabel jLabelContractResourceUnits;
    private javax.swing.JLabel jLabelTradeProfit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContract;
    private javax.swing.JTextField jTextFieldContractBribeResourceAmount;
    private javax.swing.JTextField jTextFieldContractCostPerUnit;
    private javax.swing.JTextField jTextFieldContractCostperHealthUnit;
    private javax.swing.JTextField jTextFieldContractEthicsRate;
    private javax.swing.JTextField jTextFieldContractMaximumProfit;
    private javax.swing.JTextField jTextFieldContractMaximumTime;
    private javax.swing.JTextField jTextFieldContractMinimumResourses;
    private javax.swing.JTextField jTextFieldContractName;
    private javax.swing.JTextField jTextFieldContractNumber;
    private javax.swing.JTextField jTextFieldContractProfitUnits;
    private javax.swing.JTextField jTextFieldContractResourceUnits;
    private javax.swing.JTextField jTextFieldContractValue;
    private javax.swing.JTextField jTextFieldTradeProfit;
    // End of variables declaration//GEN-END:variables
    
}
