/*
 * DatabaseLoginDialog.java
 *
 * Created on March 7, 2007, 12:53 PM
 */

package nade_project;

/**
 *This dialog allows the user to change the username and password that is used to login to mysql.
 * @author  Default
 */
public class DatabaseLoginDialog extends javax.swing.JDialog
{
    
    /** Creates new form DatabaseLoginDialog */
    private DatabaseAccessClass databaseAccessClass;

    public DatabaseLoginDialog()
    {
        databaseAccessClass = null;
        initComponents();
    }

    public DatabaseLoginDialog( DatabaseAccessClass _databaseAccessClass )
    {
        databaseAccessClass = _databaseAccessClass;
        initComponents();
        jPasswordFieldPassword.setText( databaseAccessClass.getdbPassword()   );
        jTextFieldUserName.setText(     databaseAccessClass.getdbUserName()   );
        jTextFieldMySQLURL.setText(     databaseAccessClass.getMySQLURL()     );
        jTextFieldSchema.setText(       databaseAccessClass.getdbSchemaName() );

    }

    DatabaseAccessClass getDatabaseAccessClass()
    {
        return databaseAccessClass;
    }
    void setDatabaseAccessClass( DatabaseAccessClass _databaseAccessClass )
    {
        databaseAccessClass = _databaseAccessClass;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButtonConnect = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jCheckBoxRember = new javax.swing.JCheckBox();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelMySQLURL = new javax.swing.JLabel();
        jTextFieldMySQLURL = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSchema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Database Login Dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonConnect.setText("Connect");
        jButtonConnect.setToolTipText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.setToolTipText("Cancel Connect");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jCheckBoxRember.setSelected(true);
        jCheckBoxRember.setText("Rember");
        jCheckBoxRember.setToolTipText("Remember User Name and Password");
        jCheckBoxRember.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxRember.setEnabled(false);
        jCheckBoxRember.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabelUserName.setText("User Name");

        jLabelPassword.setText("Password");

        jTextFieldUserName.setToolTipText("User Name");

        jLabelMySQLURL.setText("MySQL URL");

        jTextFieldMySQLURL.setText("jdbc:mysql:///");
        jTextFieldMySQLURL.setToolTipText("URL");

        jPasswordFieldPassword.setToolTipText("Password");

        jLabel1.setText("Schema");

        jTextFieldSchema.setText("webapps");
        jTextFieldSchema.setToolTipText("Database to connect to.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMySQLURL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConnect)
                            .addComponent(jLabel1)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelPassword))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldMySQLURL, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSchema, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel))))
                    .addComponent(jCheckBoxRember))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMySQLURL)
                    .addComponent(jTextFieldMySQLURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jCheckBoxRember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       if( databaseAccessClass != null )
       {
           databaseAccessClass.bRetry = false;
       }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
       if( databaseAccessClass != null )
       {
           databaseAccessClass.bRetry = false;
       }
       setVisible( false );
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
       if( databaseAccessClass != null )
       {
          databaseAccessClass.setdbPassword(   jPasswordFieldPassword.getText() );
          databaseAccessClass.setdbUserName(   jTextFieldUserName.getText()     );
          databaseAccessClass.setMySQLURL(     jTextFieldMySQLURL.getText()     );
          databaseAccessClass.setdbSchemaName( jTextFieldSchema.getText()       );
          if( jCheckBoxRember.isSelected() )
          {
          }
       }
       this.setVisible( false );
    }//GEN-LAST:event_jButtonConnectActionPerformed

    javax.swing.JTextField getjTextFieldMySQLURL()
    {
        return jTextFieldMySQLURL;
    }

    javax.swing.JPasswordField getjPasswordFieldPassword()
    {
        return jPasswordFieldPassword;
    }

    javax.swing.JTextField getjTextFieldUserName()
    {
        return jTextFieldUserName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JCheckBox jCheckBoxRember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMySQLURL;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldMySQLURL;
    private javax.swing.JTextField jTextFieldSchema;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
    
}
