/*
 * InformationServerClientGUI.java
 *
 * Created on March 6, 2007, 12:05 PM
 */

package nade_project;

/**
 *This class displays the interaction between information servers and the information client.
 * @author  Default
 */
public class InformationServerClientGUI extends javax.swing.JFrame
{
    
    /** Information Server Client class.*/
    InformationServerClient informationServerClient;
    
    /** NADE client class.*/
    NadeClient nadeClient;

    /**
     * Creates new form InformationServerClientGUI
     */
    public InformationServerClientGUI( NadeClient _nadeClient )
    {
        initComponents();
        nadeClient = _nadeClient;
        informationServerClient = new InformationServerClient();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessages = new javax.swing.JTextArea();
        jButtonClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jButtonAskName = new javax.swing.JButton();
        jButtonAskNumber = new javax.swing.JButton();
        jLabelIPAddress = new javax.swing.JLabel();
        jTextFieldIPAddress = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonAskContracts = new javax.swing.JButton();
        jComboBoxGroup = new javax.swing.JComboBox();
        jLabelGroup = new javax.swing.JLabel();
        jButtonRequestIP = new javax.swing.JButton();
        jLabelInfoServerIP = new javax.swing.JLabel();
        jTextFieldInfoServerIP = new javax.swing.JTextField();
        jButtonAskDisconnect = new javax.swing.JButton();

        setTitle("Information Server Client");
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextAreaMessages.setColumns(20);
        jTextAreaMessages.setEditable(false);
        jTextAreaMessages.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMessages);

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(jButtonClear))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClear)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.setEnabled(false);
        jButtonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconnectActionPerformed(evt);
            }
        });

        jButtonAskName.setText("Ask Name");
        jButtonAskName.setEnabled(false);
        jButtonAskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskNameActionPerformed(evt);
            }
        });

        jButtonAskNumber.setText("Ask Number");
        jButtonAskNumber.setEnabled(false);
        jButtonAskNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskNumberActionPerformed(evt);
            }
        });

        jLabelIPAddress.setText("IPAddress");

        jTextFieldIPAddress.setDocument(new IPDocument());
        jTextFieldIPAddress.setText("127.0.0.1");

        jLabelPort.setText("Port");

        jTextFieldPort.setText("8000");

        jButtonAskContracts.setText("Ask Contracts");
        jButtonAskContracts.setEnabled(false);
        jButtonAskContracts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskContractsActionPerformed(evt);
            }
        });

        jComboBoxGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGroupItemStateChanged(evt);
            }
        });
        jComboBoxGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGroupActionPerformed(evt);
            }
        });

        jLabelGroup.setText("Group");

        jButtonRequestIP.setText("Request Info Server IP");
        jButtonRequestIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestIPActionPerformed(evt);
            }
        });

        jLabelInfoServerIP.setText("InfoServerIP");

        jTextFieldInfoServerIP.setDocument(new IPDocument());

        jButtonAskDisconnect.setText("Ask Disconnect");
        jButtonAskDisconnect.setEnabled(false);
        jButtonAskDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAskDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDisconnect))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelGroup)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonAskName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAskNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAskContracts)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAskDisconnect)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIPAddress)
                            .addComponent(jLabelInfoServerIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldInfoServerIP)
                            .addComponent(jTextFieldIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelPort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonRequestIP))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIPAddress)
                    .addComponent(jTextFieldIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPort)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoServerIP)
                    .addComponent(jTextFieldInfoServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRequestIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGroup)
                    .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAskName)
                    .addComponent(jButtonAskNumber)
                    .addComponent(jButtonAskContracts)
                    .addComponent(jButtonAskDisconnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonDisconnect))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAskDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskDisconnectActionPerformed
       informationServerClient.AskDisconnect();
    }//GEN-LAST:event_jButtonAskDisconnectActionPerformed

    private void jButtonRequestIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestIPActionPerformed
       if( nadeClient != null )
       {
           String groupname = String.valueOf( jComboBoxGroup.getSelectedItem() );
           nadeClient.SendInfoAddressRequest( groupname );
       }
    }//GEN-LAST:event_jButtonRequestIPActionPerformed

    private void jComboBoxGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGroupItemStateChanged
       if( nadeClient != null )
       {
          String name = String.valueOf( jComboBoxGroup.getSelectedItem() );
          String ipAddress = nadeClient.GetGroupIPAddress( name ); 
          jTextFieldIPAddress.setText( ipAddress );
       }
    }//GEN-LAST:event_jComboBoxGroupItemStateChanged

    private void jComboBoxGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGroupActionPerformed
    }//GEN-LAST:event_jComboBoxGroupActionPerformed

    private void jButtonAskContractsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskContractsActionPerformed
       informationServerClient.AskContractsWon();
    }//GEN-LAST:event_jButtonAskContractsActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        try
        {
           //if( informationServerClient != null )
           //{
              informationServerClient = new InformationServerClient();

              informationServerClient.SetPort( Integer.valueOf( jTextFieldPort.getText() ) );
              informationServerClient.connect( this );
           //}
        }
        catch( Exception e )
        {
            display( "Exception: " + e.getMessage() );
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconnectActionPerformed
       informationServerClient.Disconnect();
           jButtonAskContracts.setEnabled( false );
           jButtonAskName.setEnabled( false );
           jButtonAskNumber.setEnabled( false );
           jButtonDisconnect.setEnabled( false );
           jButtonConnect.setEnabled( true );
    }//GEN-LAST:event_jButtonDisconnectActionPerformed

    private void jButtonAskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskNameActionPerformed
       informationServerClient.AskName();
    }//GEN-LAST:event_jButtonAskNameActionPerformed

    private void jButtonAskNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAskNumberActionPerformed
       informationServerClient.AskGroupNumber();
    }//GEN-LAST:event_jButtonAskNumberActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
       jTextAreaMessages.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed
    
 
    void display( String message )
    {
       jTextAreaMessages.append( message );
       jTextAreaMessages.setSelectionStart( jTextAreaMessages.getText().length() );
    }
    javax.swing.JTextArea getjTextAreaMessages()
    {
        return jTextAreaMessages;
    }
    javax.swing.JTextField getjTextFieldPort()
    {
        return jTextFieldPort;
    }
    javax.swing.JTextField getjTextFieldIPAddress()
    {
        return jTextFieldIPAddress;
    }
    javax.swing.JButton getjButtonDisconnect()
    {
        return jButtonDisconnect;
    }
    javax.swing.JButton getjButtonConnect()
    {
        return jButtonConnect;
    }
    javax.swing.JButton getjButtonAskName()
    {
        return jButtonAskName;
    }
    /**@param jButtonAskNumber*/
    javax.swing.JButton getjButtonAskNumber()
    {
        return jButtonAskNumber;
    }
    javax.swing.JButton getjButtonAskContracts()
    {
        return jButtonAskContracts;
    }
    /**@return jButtonAskDisconnect*/
    javax.swing.JButton getjButtonAskDisconnect()
    {
        return jButtonAskDisconnect;
    }
    javax.swing.JComboBox getjComboBoxGroup()
    {
       return jComboBoxGroup;
    }
    /**@return jTextFieldInfoServerIP*/
    javax.swing.JTextField getjTextFieldInfoServerIP()
    {
       return jTextFieldInfoServerIP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAskContracts;
    private javax.swing.JButton jButtonAskDisconnect;
    private javax.swing.JButton jButtonAskName;
    private javax.swing.JButton jButtonAskNumber;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonRequestIP;
    private javax.swing.JComboBox jComboBoxGroup;
    private javax.swing.JLabel jLabelGroup;
    private javax.swing.JLabel jLabelIPAddress;
    private javax.swing.JLabel jLabelInfoServerIP;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessages;
    private javax.swing.JTextField jTextFieldIPAddress;
    private javax.swing.JTextField jTextFieldInfoServerIP;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
    
}
