/*
 * MessageParserTestGUI.java
 *
 * Created on March 6, 2007, 8:19 PM
 */

package nade_project;

/**
 *This class displays the last message that was sent by NADE. It is usefull for debugging purposes.
 * @author  Default
 */
public class MessageParserTestGUI extends javax.swing.JFrame {
    
    /**Nade client class*/
    private NadeClient nadeClient;

    /**MessageParser Class.*/
    private MessageParser messageParser;

    /** Creates new form MessageParserTestGUI */
    public MessageParserTestGUI( NadeClient _nadeClient )
    {
        initComponents();
        nadeClient    = _nadeClient;
        messageParser = new MessageParser();
    }

    /**Parses the message and stores the results in the fields provided.*/
    public void Parse()
    {
       messageParser.parseMessage( jTextAreaMessage.getText() );
       jTextFieldAction.setText(   String.valueOf( messageParser.getActionNum() ) );
       jTextFieldSender.setText(   String.valueOf( messageParser.getSender()    ) );
       jTextFieldReceiver.setText( String.valueOf( messageParser.getReceiver()  ) );
       jTextFieldValue.setText(    String.valueOf( messageParser.getValue()     ) );
       jTextFieldValue1.setText(   String.valueOf( messageParser.getValue1()    ) );
       jTextFieldValue2.setText(   String.valueOf( messageParser.getValue2()    ) );

       jTextFieldContractName.setText(                String.valueOf( messageParser.getName()                ) );
       jTextFieldContractMaximumTime.setText(         String.valueOf( messageParser.getMaxTime()             ) );
       jTextFieldContractMinimumResourses.setText(    String.valueOf( messageParser.getMinResources()        ) );
       jTextFieldContractMaximumProfit.setText(       String.valueOf( messageParser.getMaxProfit()           ) );
       jTextFieldContractCostPerUnit.setText(         String.valueOf( messageParser.getCostPerUnit()         ) );
       jTextFieldContractCostperHealthUnit.setText(   String.valueOf( messageParser.getCostPerHealthUnit()   ) );
       jTextFieldContractBribeResourceAmount.setText( String.valueOf( messageParser.getBribeResourceAmount() ) );
       jTextFieldContractEthicsRate.setText(          String.valueOf( messageParser.getEthicsRate()          ) );
       jTextFieldContractResourceUnits.setText(       String.valueOf( messageParser.getResourceUnits()       ) );
       jTextFieldContractProfitUnits.setText(         String.valueOf( messageParser.getProfitUnits()         ) );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jPanelMessage = new javax.swing.JPanel();
        jLabelReciever = new javax.swing.JLabel();
        jLabelSender = new javax.swing.JLabel();
        jLabelAction = new javax.swing.JLabel();
        jLabelValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelValue2 = new javax.swing.JLabel();
        jTextFieldValue1 = new javax.swing.JTextField();
        jTextFieldValue = new javax.swing.JTextField();
        jTextFieldReceiver = new javax.swing.JTextField();
        jTextFieldAction = new javax.swing.JTextField();
        jTextFieldSender = new javax.swing.JTextField();
        jTextFieldValue2 = new javax.swing.JTextField();
        jTextFieldRegex = new javax.swing.JTextField();
        jLabelRegex = new javax.swing.JLabel();
        jTextFieldTestString = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldMatch = new javax.swing.JTextField();
        jPanelContract = new javax.swing.JPanel();
        jLabelContractName = new javax.swing.JLabel();
        jTextFieldContractName = new javax.swing.JTextField();
        jTextFieldContractMaximumTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldContractMinimumResourses = new javax.swing.JTextField();
        jLabelContractMinimumResourses = new javax.swing.JLabel();
        jLabelContractMaximumProfit = new javax.swing.JLabel();
        jTextFieldContractMaximumProfit = new javax.swing.JTextField();
        jLabelContractCostPerUnit = new javax.swing.JLabel();
        jTextFieldContractCostPerUnit = new javax.swing.JTextField();
        jLabelContractCostPerHealthUnit = new javax.swing.JLabel();
        jTextFieldContractCostperHealthUnit = new javax.swing.JTextField();
        jLabelContractBribeResourceAmount = new javax.swing.JLabel();
        jTextFieldContractBribeResourceAmount = new javax.swing.JTextField();
        jLabelContractEthicsRate = new javax.swing.JLabel();
        jTextFieldContractEthicsRate = new javax.swing.JTextField();
        jLabelContractResourceUnits = new javax.swing.JLabel();
        jTextFieldContractResourceUnits = new javax.swing.JTextField();
        jLabelContractProfitUnits = new javax.swing.JLabel();
        jTextFieldContractProfitUnits = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonParse = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();

        setTitle("Message Parser Test");
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonClear.setText("Clear");

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setEditable(false);
        jTextAreaMessage.setRows(5);
        jScrollPaneMessage.setViewportView(jTextAreaMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClear)
                    .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClear)
                .addContainerGap())
        );

        jPanelMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelReciever.setText("Receiver");

        jLabelSender.setText("Sender");

        jLabelAction.setText("Action");

        jLabelValue.setText("Value");

        jLabel1.setText("Value1");

        jLabelValue2.setText("Value2");

        jLabelRegex.setText("Regex");

        jLabel3.setText("Test String");

        jButton1.setText("Match");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldMatch.setEditable(false);
        jTextFieldMatch.setText("No Match Occured");

        javax.swing.GroupLayout jPanelMessageLayout = new javax.swing.GroupLayout(jPanelMessage);
        jPanelMessage.setLayout(jPanelMessageLayout);
        jPanelMessageLayout.setHorizontalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReciever)
                    .addComponent(jLabelSender)
                    .addComponent(jLabelAction)
                    .addComponent(jLabelValue)
                    .addComponent(jLabelValue2)
                    .addComponent(jLabel1)
                    .addComponent(jLabelRegex)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jTextFieldReceiver, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jTextFieldSender, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jTextFieldValue2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jTextFieldAction, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldTestString, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldRegex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(jTextFieldMatch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMessageLayout.setVerticalGroup(
            jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAction)
                    .addComponent(jTextFieldAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReciever)
                    .addComponent(jTextFieldReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValue)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValue2)
                    .addComponent(jTextFieldValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTestString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelContract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelContractName.setText("Name");

        jTextFieldContractName.setEditable(false);

        jTextFieldContractMaximumTime.setEditable(false);

        jLabel2.setText("Maximum Time");

        jTextFieldContractMinimumResourses.setEditable(false);

        jLabelContractMinimumResourses.setText("Minimum Resourses");

        jLabelContractMaximumProfit.setText("Maximum Profit");

        jTextFieldContractMaximumProfit.setEditable(false);

        jLabelContractCostPerUnit.setText("Cost Per Unit");

        jTextFieldContractCostPerUnit.setEditable(false);

        jLabelContractCostPerHealthUnit.setText("Cost Per Health Unit");

        jTextFieldContractCostperHealthUnit.setEditable(false);

        jLabelContractBribeResourceAmount.setText("Bribe Resource Amount");

        jTextFieldContractBribeResourceAmount.setEditable(false);

        jLabelContractEthicsRate.setText("Ethics Rate");

        jTextFieldContractEthicsRate.setEditable(false);

        jLabelContractResourceUnits.setText("Resource Units Added");

        jTextFieldContractResourceUnits.setEditable(false);

        jLabelContractProfitUnits.setText("Profit Units Added");

        jTextFieldContractProfitUnits.setEditable(false);

        javax.swing.GroupLayout jPanelContractLayout = new javax.swing.GroupLayout(jPanelContract);
        jPanelContract.setLayout(jPanelContractLayout);
        jPanelContractLayout.setHorizontalGroup(
            jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractBribeResourceAmount)
                    .addComponent(jLabelContractCostPerHealthUnit)
                    .addComponent(jLabelContractName)
                    .addComponent(jLabel2)
                    .addComponent(jLabelContractMinimumResourses)
                    .addComponent(jLabelContractMaximumProfit)
                    .addComponent(jLabelContractCostPerUnit)
                    .addComponent(jLabelContractEthicsRate)
                    .addComponent(jLabelContractResourceUnits)
                    .addComponent(jLabelContractProfitUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContractLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldContractMinimumResourses, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractMaximumTime, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractName, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jTextFieldContractMaximumProfit, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .addComponent(jTextFieldContractCostPerUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextFieldContractCostperHealthUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextFieldContractBribeResourceAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextFieldContractEthicsRate, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextFieldContractResourceUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jTextFieldContractProfitUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelContractLayout.setVerticalGroup(
            jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractName)
                    .addComponent(jTextFieldContractName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContractMaximumTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContractMinimumResourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContractMinimumResourses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractMaximumProfit)
                    .addComponent(jTextFieldContractMaximumProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractCostPerUnit)
                    .addComponent(jTextFieldContractCostPerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractCostPerHealthUnit)
                    .addComponent(jTextFieldContractCostperHealthUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractBribeResourceAmount)
                    .addComponent(jTextFieldContractBribeResourceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractEthicsRate)
                    .addComponent(jTextFieldContractEthicsRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractResourceUnits)
                    .addComponent(jTextFieldContractResourceUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContractProfitUnits)
                    .addComponent(jTextFieldContractProfitUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonParse.setText("Parse");
        jButtonParse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParseActionPerformed(evt);
            }
        });

        jLabelDescription.setText("This parses is the last message sent by the Nade Server.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonParse)
                .addGap(25, 25, 25)
                .addComponent(jLabelDescription)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButtonParse)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescription)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**Test a regex with a string.*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if( jTextFieldTestString.getText().matches( jTextFieldRegex.getText() ) )
       {
           jTextFieldMatch.setText( "Match Occured" );
       }
       else
       {
           jTextFieldMatch.setText( "No Match Occured" );
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**Parses the message and stores the results in the fields provided.*/
    private void jButtonParseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParseActionPerformed
       messageParser.parseMessage( jTextAreaMessage.getText() );
       jTextFieldAction.setText(   String.valueOf( messageParser.getActionNum() ) );
       jTextFieldSender.setText(   String.valueOf( messageParser.getSender()    ) );
       jTextFieldReceiver.setText( String.valueOf( messageParser.getReceiver()  ) );
       jTextFieldValue.setText(    String.valueOf( messageParser.getValue()     ) );
       jTextFieldValue1.setText(   String.valueOf( messageParser.getValue1()    ) );
       jTextFieldValue2.setText(   String.valueOf( messageParser.getValue2()    ) );

       jTextFieldContractName.setText(                String.valueOf( messageParser.getName()                ) );
       jTextFieldContractMaximumTime.setText(         String.valueOf( messageParser.getMaxTime()             ) );
       jTextFieldContractMinimumResourses.setText(    String.valueOf( messageParser.getMinResources()        ) );
       jTextFieldContractMaximumProfit.setText(       String.valueOf( messageParser.getMaxProfit()           ) );
       jTextFieldContractCostPerUnit.setText(         String.valueOf( messageParser.getCostPerUnit()         ) );
       jTextFieldContractCostperHealthUnit.setText(   String.valueOf( messageParser.getCostPerHealthUnit()   ) );
       jTextFieldContractBribeResourceAmount.setText( String.valueOf( messageParser.getBribeResourceAmount() ) );
       jTextFieldContractEthicsRate.setText(          String.valueOf( messageParser.getEthicsRate()          ) );
       jTextFieldContractResourceUnits.setText(       String.valueOf( messageParser.getResourceUnits()       ) );
       jTextFieldContractProfitUnits.setText(         String.valueOf( messageParser.getProfitUnits()         ) );       
    }//GEN-LAST:event_jButtonParseActionPerformed

    /**@return jTextAreaMessage*/
    public javax.swing.JTextArea getjTextAreaMessage()
    {
        return jTextAreaMessage;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonParse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAction;
    private javax.swing.JLabel jLabelContractBribeResourceAmount;
    private javax.swing.JLabel jLabelContractCostPerHealthUnit;
    private javax.swing.JLabel jLabelContractCostPerUnit;
    private javax.swing.JLabel jLabelContractEthicsRate;
    private javax.swing.JLabel jLabelContractMaximumProfit;
    private javax.swing.JLabel jLabelContractMinimumResourses;
    private javax.swing.JLabel jLabelContractName;
    private javax.swing.JLabel jLabelContractProfitUnits;
    private javax.swing.JLabel jLabelContractResourceUnits;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelReciever;
    private javax.swing.JLabel jLabelRegex;
    private javax.swing.JLabel jLabelSender;
    private javax.swing.JLabel jLabelValue;
    private javax.swing.JLabel jLabelValue2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelContract;
    private javax.swing.JPanel jPanelMessage;
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldAction;
    private javax.swing.JTextField jTextFieldContractBribeResourceAmount;
    private javax.swing.JTextField jTextFieldContractCostPerUnit;
    private javax.swing.JTextField jTextFieldContractCostperHealthUnit;
    private javax.swing.JTextField jTextFieldContractEthicsRate;
    private javax.swing.JTextField jTextFieldContractMaximumProfit;
    private javax.swing.JTextField jTextFieldContractMaximumTime;
    private javax.swing.JTextField jTextFieldContractMinimumResourses;
    private javax.swing.JTextField jTextFieldContractName;
    private javax.swing.JTextField jTextFieldContractProfitUnits;
    private javax.swing.JTextField jTextFieldContractResourceUnits;
    private javax.swing.JTextField jTextFieldMatch;
    private javax.swing.JTextField jTextFieldReceiver;
    private javax.swing.JTextField jTextFieldRegex;
    private javax.swing.JTextField jTextFieldSender;
    private javax.swing.JTextField jTextFieldTestString;
    private javax.swing.JTextField jTextFieldValue;
    private javax.swing.JTextField jTextFieldValue1;
    private javax.swing.JTextField jTextFieldValue2;
    // End of variables declaration//GEN-END:variables
    
}
