/*
 * NadeProjectGUIInterface.java
 *
 * Created on February 22, 2007, 9:44 PM
 */

package nade_project;

import java.io.*;
import nade_project.NadeClient;
import javax.swing.text.*;
import javax.swing.text.html.*;
import javax.swing.*;


/**
 *This dialog is the main interface the user has with the nade client.
 * @author  Default
 */
public class NadeProjectGUIInterface extends javax.swing.JFrame
{
    
    /**Nade client class.*/
    NadeClient nadeClient;

    /**INI File*/
    public INIFile iniFile;

    /**Settings File name*/
    public String settingsFileName;

    /** Creates new form NadeProjectGUIInterface */
    public NadeProjectGUIInterface()
    {
        initComponents();

        nadeClient       = null;
        settingsFileName = "settings.ini";

        try
        {
           //jEditorPaneLog.setContentType( "text/plain" );
           jEditorPaneLog.setContentType( "text/html" );
           jEditorPaneLog.setText( "<html></html>" );
        }
        catch( Exception e )
        {
           System.out.println( "Exception: " + e.getMessage() );
        }

        try
        {
           iniFile = new INIFile( settingsFileName );
        }
        catch( Exception e )
        {
           System.out.println( "Exception: " + e.getMessage() );
        }
        try
        {
              String temp = "";
              if( iniFile.getStringProperty( "NADE", "serverip"   ) != null )
              {
                 temp = iniFile.getStringProperty( "NADE", "serverip"   );
              }
              getjFormattedTextFieldIPAddress().setText( temp );
              if( iniFile.getStringProperty( "NADE", "serverport"   ) != null )
              {
                 temp = iniFile.getStringProperty( "NADE", "serverport"   );
              }
              try
              {
                 Integer.parseInt( temp );
              }
              catch( NumberFormatException exception )
              {
                 temp = "5000";
              }
              getjFormattedTextFieldPort().setText( temp );
              if( iniFile.getStringProperty( "Settings", "name"   ) != null )
              {
                 temp = iniFile.getStringProperty( "Settings", "name"   );
              }
              getjTextFieldPublicName().setText( temp );
        }
        catch( Exception e )
        {
            display( "NadeProjectGUIInterface.NadeProjectGUIInterface - Exception: " + e.getMessage() );
        }
    }

    /**Connect to NADE server.*/
    public void ConnectToNADE()
    {
       try
       {
          if( nadeClient != null )
          {
              nadeClient.stopClient();
          }
          nadeClient = new NadeClient( this );
          nadeClient.runClient( this );
       }
       catch( IllegalThreadStateException e )
       {
           //jEditorPaneLog.append( e.getMessage() );
           display( "IllegalThreadStateException: " + e.getMessage() );
       }
       catch( Exception e )
       {
          //jEditorPaneLog.append( e.getMessage() );
           display( "Exception: " + e.getMessage() );
       }
    }

    /**This selects the text in the addtional bid amount text field.*/
    public void SelectAdditionalBidAmount()
    {
       jTextFieldAdditionalBidAmount.setSelectionStart( 0 );
       jTextFieldAdditionalBidAmount.setSelectionEnd( jTextFieldAdditionalBidAmount.getText().length() );
    }

    /**Displays a message
     *@param message message to display.
     */
    public void display( String message )
    {
        try
        {
           message = message.replaceAll( "</html>", "" );

           HTMLEditorKit      kit = (HTMLEditorKit) jEditorPaneLog.getEditorKit();
           Document      document = jEditorPaneLog.getDocument();
           StringReader    reader = new StringReader( "<font size='5'>" + message + "</font>" + "<br>" );
           kit.read( reader, document, document.getLength() );
           if( !jEditorPaneLog.isFocusOwner() )
           {
              jEditorPaneLog.setSelectionStart( document.getLength() );
           }
            
           //SimpleAttributeSet attributes = new SimpleAttributeSet();
           //Document      document = jEditorPaneLog.getDocument();
           //document.insertString( document.getLength(), message + "\n", attributes );
           //jEditorPaneLog.setSelectionStart( document.getLength() );
        }
        catch( Exception e )
        {
           System.out.println( "NadeProjectGUIInterface.display - Exception: " + e.getMessage() );
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jFormattedTextFieldIPAddress = new javax.swing.JFormattedTextField();
        jLabelNadeServerIPAddress = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jFormattedTextFieldPort = new javax.swing.JFormattedTextField();
        jFormattedTextFieldLocalIPAddress = new javax.swing.JFormattedTextField();
        jLabelLocalIPAddress = new javax.swing.JLabel();
        jLabelPublicName = new javax.swing.JLabel();
        jTextFieldPublicName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTheirMoney = new javax.swing.JTextField();
        choiceGroups = new java.awt.Choice();
        jLabelGroup = new javax.swing.JLabel();
        jLabelTheirHealth = new javax.swing.JLabel();
        jTextFieldTheirResources = new javax.swing.JTextField();
        jLabelTheirResources = new javax.swing.JLabel();
        jLabelTheirContracts = new javax.swing.JLabel();
        jTextFieldTheirContracts = new javax.swing.JTextField();
        jTextFieldTheirHealth = new javax.swing.JTextField();
        jButtonInformationServer = new javax.swing.JButton();
        jButtonChat = new javax.swing.JButton();
        jTextFieldTheirIPAddress = new javax.swing.JTextField();
        jLabelIPAddress = new javax.swing.JLabel();
        jCheckBoxBlock = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldOurMoney = new javax.swing.JTextField();
        jLabelOurMoney = new javax.swing.JLabel();
        jLabelOurHealth = new javax.swing.JLabel();
        jTextFieldOurHealth = new javax.swing.JTextField();
        jTextFieldOurResources = new javax.swing.JTextField();
        jLabelOurResources = new javax.swing.JLabel();
        jLabelBidAmount = new javax.swing.JLabel();
        jTextFieldBidAmount = new javax.swing.JTextField();
        jButtonMakeBid = new javax.swing.JButton();
        jButtonHealth = new javax.swing.JButton();
        jTextFieldRestoreHealth = new javax.swing.JTextField();
        jLabelRestoreHealth = new javax.swing.JLabel();
        jLabelOurContracts = new javax.swing.JLabel();
        jTextFieldOurContracts = new javax.swing.JTextField();
        jTextFieldControlResources = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelControlMoney = new javax.swing.JLabel();
        jTextFieldControlMoney = new javax.swing.JTextField();
        jTextFieldGameLength = new javax.swing.JTextField();
        jLabelGameLength = new javax.swing.JLabel();
        jButtonBribe = new javax.swing.JButton();
        jCheckBoxAutoPilot = new javax.swing.JCheckBox();
        jButtonSecurity = new javax.swing.JButton();
        jButtonRumour = new javax.swing.JButton();
        jCheckBoxInformationServerRunning = new javax.swing.JCheckBox();
        jButtonAutoPilotOptions = new javax.swing.JButton();
        jTextFieldAdditionalBidAmount = new javax.swing.JTextField();
        jCheckBoxConnectedToDatabase = new javax.swing.JCheckBox();
        jSliderAdditionalBidAmount = new javax.swing.JSlider();
        jPanelShowMessageParserTest = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonShowContractInfo = new javax.swing.JButton();
        jButtonTradeInfo = new javax.swing.JButton();
        jButtonBankingInfo = new javax.swing.JButton();
        jButtonStandings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneLog = new javax.swing.JEditorPane();
        jButtonMessageParserTest = new javax.swing.JButton();
        jButtonStartNade = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nade Project GUI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonConnect.setText("Connect");
        jButtonConnect.setToolTipText(" to NADE server.");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.setToolTipText("Disconnect from NADE server.");
        jButtonDisconnect.setEnabled(false);
        jButtonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconnectActionPerformed(evt);
            }
        });

        jFormattedTextFieldIPAddress.setDocument(new IPDocument());
        jFormattedTextFieldIPAddress.setText("127.0.0.1");
        jFormattedTextFieldIPAddress.setToolTipText("IP of nade server.");
        jFormattedTextFieldIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldIPAddressKeyReleased(evt);
            }
        });

        jLabelNadeServerIPAddress.setText("Server IP Address");

        jLabelPort.setText("Port");

        jFormattedTextFieldPort.setDocument(new IntegerDocument());
        jFormattedTextFieldPort.setText("5000");
        jFormattedTextFieldPort.setToolTipText("Nade server port.");
        jFormattedTextFieldPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPortKeyReleased(evt);
            }
        });

        jFormattedTextFieldLocalIPAddress.setEditable(false);
        jFormattedTextFieldLocalIPAddress.setText("127.0.0.1");
        jFormattedTextFieldLocalIPAddress.setToolTipText("Local IP address.");

        jLabelLocalIPAddress.setText("Local IP Address");

        jLabelPublicName.setText("Public Name");

        jTextFieldPublicName.setText("Glasdak");
        jTextFieldPublicName.setToolTipText("Name other groups will Identify this client by. Glasdak stands for Gabrielle, Linstron, Andre, Shelly, Deloris, Andre and Kirk");
        jTextFieldPublicName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPublicNameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDisconnect))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelNadeServerIPAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldIPAddress)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLocalIPAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPublicName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPublicName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextFieldLocalIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNadeServerIPAddress)
                    .addComponent(jFormattedTextFieldIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPort)
                    .addComponent(jFormattedTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPublicName)
                    .addComponent(jTextFieldPublicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDisconnect)
                    .addComponent(jButtonConnect)
                    .addComponent(jLabelLocalIPAddress)
                    .addComponent(jFormattedTextFieldLocalIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Money");

        jTextFieldTheirMoney.setDocument(new DoubleDocument());
        jTextFieldTheirMoney.setEditable(false);
        jTextFieldTheirMoney.setText("0");
        jTextFieldTheirMoney.setToolTipText("Money this group has (estimate)");

        choiceGroups.setEnabled(false);
        choiceGroups.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceGroupsItemStateChanged(evt);
            }
        });
        choiceGroups.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                choiceGroupsFocusGained(evt);
            }
        });

        jLabelGroup.setText("Other Group");

        jLabelTheirHealth.setText("Health");

        jTextFieldTheirResources.setDocument(new IntegerDocument());
        jTextFieldTheirResources.setEditable(false);
        jTextFieldTheirResources.setText("0");
        jTextFieldTheirResources.setToolTipText("Resources this group has (estimate).");

        jLabelTheirResources.setText("Resources");

        jLabelTheirContracts.setText("Contracts");

        jTextFieldTheirContracts.setDocument(new IntegerDocument());
        jTextFieldTheirContracts.setEditable(false);
        jTextFieldTheirContracts.setText("0");
        jTextFieldTheirContracts.setToolTipText("Contracts won by this group.");

        jTextFieldTheirHealth.setDocument(new IntegerDocument());
        jTextFieldTheirHealth.setEditable(false);
        jTextFieldTheirHealth.setText("0");

        jButtonInformationServer.setText("Information Server Client");
        jButtonInformationServer.setToolTipText("Connect to groups information server.");
        jButtonInformationServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformationServerActionPerformed(evt);
            }
        });

        jButtonChat.setText("Chat");
        jButtonChat.setToolTipText("Chat with group.");
        jButtonChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChatActionPerformed(evt);
            }
        });

        jTextFieldTheirIPAddress.setDocument(new IPDocument());
        jTextFieldTheirIPAddress.setEditable(false);
        jTextFieldTheirIPAddress.setText("0.0.0.0");

        jLabelIPAddress.setText("IP");

        jCheckBoxBlock.setText("Block");
        jCheckBoxBlock.setToolTipText("Block all messages from this client.");
        jCheckBoxBlock.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxBlock.setEnabled(false);
        jCheckBoxBlock.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBlockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTheirResources)
                    .addComponent(jLabelGroup)
                    .addComponent(jLabelIPAddress)
                    .addComponent(jCheckBoxBlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(choiceGroups, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonChat, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldTheirIPAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldTheirMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldTheirResources, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTheirContracts, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTheirHealth, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTheirHealth, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTheirContracts, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addComponent(jButtonInformationServer, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGroup))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTheirHealth)
                    .addComponent(jTextFieldTheirMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTheirHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTheirResources)
                    .addComponent(jTextFieldTheirResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTheirContracts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTheirContracts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIPAddress)
                    .addComponent(jTextFieldTheirIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBlock)
                    .addComponent(jButtonChat)
                    .addComponent(jButtonInformationServer))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldOurMoney.setDocument(new DoubleDocument());
        jTextFieldOurMoney.setEditable(false);
        jTextFieldOurMoney.setText("0");
        jTextFieldOurMoney.setToolTipText("Our groups profit.");

        jLabelOurMoney.setText("Money");

        jLabelOurHealth.setText("Health");

        jTextFieldOurHealth.setDocument(new DoubleDocument());
        jTextFieldOurHealth.setEditable(false);
        jTextFieldOurHealth.setText("0");
        jTextFieldOurHealth.setToolTipText("Our groups Health.");

        jTextFieldOurResources.setDocument(new IntegerDocument());
        jTextFieldOurResources.setEditable(false);
        jTextFieldOurResources.setText("0");

        jLabelOurResources.setText("Resources");

        jLabelBidAmount.setText("Bid Amount");

        jTextFieldBidAmount.setDocument(new IntegerDocument());
        jTextFieldBidAmount.setEditable(false);
        jTextFieldBidAmount.setText("0");
        jTextFieldBidAmount.setToolTipText("Minimum resources allocated to bid.");

        jButtonMakeBid.setText("Make Bid");
        jButtonMakeBid.setToolTipText("Make a bid for the next contract.");
        jButtonMakeBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeBidActionPerformed(evt);
            }
        });

        jButtonHealth.setText("Restore Health");
        jButtonHealth.setToolTipText("Restore health.");
        jButtonHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHealthActionPerformed(evt);
            }
        });

        jTextFieldRestoreHealth.setDocument(new IntegerDocument());
        jTextFieldRestoreHealth.setEditable(false);
        jTextFieldRestoreHealth.setText("0");
        jTextFieldRestoreHealth.setToolTipText("Cost per health unit (resources).");

        jLabelRestoreHealth.setText("Restore Health");

        jLabelOurContracts.setText("Contracts");

        jTextFieldOurContracts.setDocument(new IntegerDocument());
        jTextFieldOurContracts.setEditable(false);
        jTextFieldOurContracts.setText("0");

        jTextFieldControlResources.setDocument(new DoubleDocument());
        jTextFieldControlResources.setEditable(false);
        jTextFieldControlResources.setText("0");
        jTextFieldControlResources.setToolTipText("Control Resources.");

        jLabel5.setText("Control Resources");

        jLabelControlMoney.setText("Control Money");

        jTextFieldControlMoney.setDocument(new DoubleDocument());
        jTextFieldControlMoney.setEditable(false);
        jTextFieldControlMoney.setText("0");
        jTextFieldControlMoney.setToolTipText("Control Money.");

        jTextFieldGameLength.setDocument(new DoubleDocument());
        jTextFieldGameLength.setEditable(false);
        jTextFieldGameLength.setText("0");
        jTextFieldGameLength.setToolTipText("Game Length");

        jLabelGameLength.setText("Game Length");

        jButtonBribe.setText("Bribe");
        jButtonBribe.setToolTipText("Bribing is pratically pointless =/");
        jButtonBribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBribeActionPerformed(evt);
            }
        });

        jCheckBoxAutoPilot.setSelected(true);
        jCheckBoxAutoPilot.setText("AutoBidder");
        jCheckBoxAutoPilot.setToolTipText("Auto Bidding.");
        jCheckBoxAutoPilot.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxAutoPilot.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxAutoPilot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAutoPilotActionPerformed(evt);
            }
        });

        jButtonSecurity.setText("Security");
        jButtonSecurity.setToolTipText("Try to crash someone elses client =)");
        jButtonSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecurityActionPerformed(evt);
            }
        });

        jButtonRumour.setText("Rumour");
        jButtonRumour.setToolTipText("Send rumour.");
        jButtonRumour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRumourActionPerformed(evt);
            }
        });

        jCheckBoxInformationServerRunning.setText("Information Server Running");
        jCheckBoxInformationServerRunning.setToolTipText("Is the information server running?");
        jCheckBoxInformationServerRunning.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxInformationServerRunning.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxInformationServerRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInformationServerRunningActionPerformed(evt);
            }
        });

        jButtonAutoPilotOptions.setText("Options");
        jButtonAutoPilotOptions.setToolTipText("Auto pilot options. (Autto bidding)");
        jButtonAutoPilotOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoPilotOptionsActionPerformed(evt);
            }
        });

        jTextFieldAdditionalBidAmount.setDocument(new IntegerDocument());
        jTextFieldAdditionalBidAmount.setText("50");
        jTextFieldAdditionalBidAmount.setToolTipText("Additional resources needed to outbid others.");
        jTextFieldAdditionalBidAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAdditionalBidAmountKeyTyped(evt);
            }
        });

        jCheckBoxConnectedToDatabase.setText("Connected to Database");
        jCheckBoxConnectedToDatabase.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxConnectedToDatabase.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBoxConnectedToDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxConnectedToDatabaseActionPerformed(evt);
            }
        });

        jSliderAdditionalBidAmount.setMaximum(1000);
        jSliderAdditionalBidAmount.setToolTipText("Additional resources.");
        jSliderAdditionalBidAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAdditionalBidAmountStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelOurMoney)
                                    .addComponent(jLabelOurHealth)
                                    .addComponent(jLabelRestoreHealth))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRestoreHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOurHealth, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOurMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jButtonAutoPilotOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBoxAutoPilot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBoxInformationServerRunning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelOurResources)
                                    .addComponent(jLabelOurContracts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldOurResources, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOurContracts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                            .addComponent(jButtonHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jButtonRumour, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSecurity, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jButtonBribe, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelControlMoney)
                                .addComponent(jLabel5)
                                .addComponent(jLabelGameLength)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldGameLength, 0, 0, Short.MAX_VALUE)
                            .addComponent(jTextFieldControlMoney, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldControlResources, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelBidAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAdditionalBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jCheckBoxConnectedToDatabase, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderAdditionalBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMakeBid)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOurMoney)
                    .addComponent(jTextFieldOurMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldControlResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOurResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOurResources))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOurHealth)
                    .addComponent(jTextFieldOurHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldControlMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelControlMoney)
                    .addComponent(jTextFieldOurContracts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOurContracts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGameLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGameLength)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRestoreHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRestoreHealth)
                            .addComponent(jButtonHealth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonAutoPilotOptions)
                                .addComponent(jButtonRumour)
                                .addComponent(jButtonBribe))
                            .addComponent(jCheckBoxAutoPilot))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxInformationServerRunning)
                    .addComponent(jButtonSecurity))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxConnectedToDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBidAmount)
                            .addComponent(jTextFieldBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdditionalBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMakeBid)
                            .addComponent(jSliderAdditionalBidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        jPanelShowMessageParserTest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonClear.setText("Clear");
        jButtonClear.setToolTipText("Clear messages.");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonShowContractInfo.setText("Contract Info");
        jButtonShowContractInfo.setToolTipText("View the information about the current contract.");
        jButtonShowContractInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowContractInfoActionPerformed(evt);
            }
        });

        jButtonTradeInfo.setText("Trade Info");
        jButtonTradeInfo.setToolTipText("Buy and sell resources from the control.");
        jButtonTradeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTradeInfoActionPerformed(evt);
            }
        });

        jButtonBankingInfo.setText("Banking Info");
        jButtonBankingInfo.setToolTipText("Trade resources between other groups.");
        jButtonBankingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBankingInfoActionPerformed(evt);
            }
        });

        jButtonStandings.setText("Standings");
        jButtonStandings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStandingsActionPerformed(evt);
            }
        });

        jEditorPaneLog.setEditable(false);
        jEditorPaneLog.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jScrollPane1.setViewportView(jEditorPaneLog);

        jButtonMessageParserTest.setText("Show Message Parser Test");
        jButtonMessageParserTest.setToolTipText("Test ability to parse messages.");
        jButtonMessageParserTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMessageParserTestActionPerformed(evt);
            }
        });

        jButtonStartNade.setText("Start Nade");
        jButtonStartNade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartNadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShowMessageParserTestLayout = new javax.swing.GroupLayout(jPanelShowMessageParserTest);
        jPanelShowMessageParserTest.setLayout(jPanelShowMessageParserTestLayout);
        jPanelShowMessageParserTestLayout.setHorizontalGroup(
            jPanelShowMessageParserTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowMessageParserTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShowMessageParserTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelShowMessageParserTestLayout.createSequentialGroup()
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonShowContractInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTradeInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBankingInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStandings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMessageParserTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStartNade)))
                .addContainerGap())
        );
        jPanelShowMessageParserTestLayout.setVerticalGroup(
            jPanelShowMessageParserTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowMessageParserTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShowMessageParserTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonShowContractInfo)
                    .addComponent(jButtonTradeInfo)
                    .addComponent(jButtonBankingInfo)
                    .addComponent(jButtonStandings)
                    .addComponent(jButtonMessageParserTest)
                    .addComponent(jButtonStartNade))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelShowMessageParserTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelShowMessageParserTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonStartNadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartNadeActionPerformed

   //java -classpath .;"lib\nade.jar" nade.server.NDServer
   //java -classpath .;"lib\nade.jar" nade.control.NDDefaultControl
   try
   {
      String      userDir = System.getProperty( "user.dir" );
      Runtime           r = Runtime.getRuntime();

      boolean bFoundNADEInCurrentDir = false;
      File NADELib = new File( userDir + "\\nade.jar" );

      bFoundNADEInCurrentDir = NADELib.exists();
      if( bFoundNADEInCurrentDir )
      {
         Process nadeserver  = r.exec( "javaw -classpath .;\"" + userDir + "/nade.jar\" nade.server.NDServer" );
         Process nadecontrol = r.exec( "javaw -classpath .;\"" + userDir + "/nade.jar\" nade.control.NDDefaultControl" );
      }
      else
      {
         Process nadeserver  = r.exec( "javaw -classpath .;\"" + userDir + "\\lib\\nade.jar\" nade.server.NDServer" );
         Process nadecontrol = r.exec( "javaw -classpath .;\"" + userDir + "\\lib\\nade.jar\" nade.control.NDDefaultControl" );
      }
   }
   catch( IOException e )
   {
      display( "NADE failed to start: " + e.getMessage() );
   }
   //catch( InterruptedException e )
   //{
   //   display( "NADE failed to start: " + e.getMessage() );
   //}
}//GEN-LAST:event_jButtonStartNadeActionPerformed

    private void jSliderAdditionalBidAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAdditionalBidAmountStateChanged
       if( nadeClient != null )
       {
          jTextFieldAdditionalBidAmount.setText( String.valueOf( jSliderAdditionalBidAmount.getValue() ) );
          SelectAdditionalBidAmount();
       }
    }//GEN-LAST:event_jSliderAdditionalBidAmountStateChanged

    private void jCheckBoxInformationServerRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInformationServerRunningActionPerformed
       if( nadeClient != null )
       {
          if( jCheckBoxInformationServerRunning.isSelected() )
          {
             nadeClient.StartInformationServer();
          }
          else
          {
             nadeClient.StopInformationServer();
          }
       }
    }//GEN-LAST:event_jCheckBoxInformationServerRunningActionPerformed

    /***/
    private void jCheckBoxConnectedToDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxConnectedToDatabaseActionPerformed

       if( nadeClient != null )
       {
          if( jCheckBoxConnectedToDatabase.isSelected() )
          {
             nadeClient.databaseAccessClass.Connect( nadeClient );
          }
          else
          {
             nadeClient.databaseAccessClass.Disconnect();
          }
       }
    }//GEN-LAST:event_jCheckBoxConnectedToDatabaseActionPerformed

    private void jTextFieldPublicNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPublicNameKeyReleased
       if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER )
       {
          //ConnectToNADE();
       }
    }//GEN-LAST:event_jTextFieldPublicNameKeyReleased

    private void jFormattedTextFieldPortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPortKeyReleased
       if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER )
       {
          ConnectToNADE();
       }
    }//GEN-LAST:event_jFormattedTextFieldPortKeyReleased

    private void jFormattedTextFieldIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIPAddressKeyReleased
       if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER )
       {
          ConnectToNADE();
       }
    }//GEN-LAST:event_jFormattedTextFieldIPAddressKeyReleased

    private void jTextFieldAdditionalBidAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdditionalBidAmountKeyTyped
       if( nadeClient != null )
       {
          if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER )
          {
             nadeClient.MakeBid();
             SelectAdditionalBidAmount();
          }
       }
    }//GEN-LAST:event_jTextFieldAdditionalBidAmountKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
           try
           {
              iniFile.setStringProperty(     "NADE",   "serverip", getjFormattedTextFieldIPAddress().getText(), "none" );
              iniFile.setStringProperty(     "NADE", "serverport",      getjFormattedTextFieldPort().getText(), "none" );
              iniFile.setStringProperty( "Settings",       "name",         getjTextFieldPublicName().getText(), "none" );
              iniFile.save();
              if( nadeClient != null )
              {
                 //nadeClient.databaseAccessClass.Disconnect();
                 nadeClient.stopClient();
              }
           }
           catch( Exception e )
           {
              display( "NadeProjectGUIInterface.formWindowClosed - Exception: " + e.getMessage() );
           }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonStandingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStandingsActionPerformed
       if( nadeClient != null )
       {
          nadeClient.ShowStandingsDialog();
       }
    }//GEN-LAST:event_jButtonStandingsActionPerformed

    private void jCheckBoxBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBlockActionPerformed
       if( nadeClient != null )
       {
          if( this.jCheckBoxBlock.isSelected() )
          {
             nadeClient.BlockGroup( choiceGroups.getSelectedItem(), true );
          }
          else
          {
             nadeClient.BlockGroup( choiceGroups.getSelectedItem(), false );
          }
       }
    }//GEN-LAST:event_jCheckBoxBlockActionPerformed

    private void jButtonAutoPilotOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoPilotOptionsActionPerformed
       if( nadeClient != null )
       {
          nadeClient.ShowAutoPilotOptions();
       }
    }//GEN-LAST:event_jButtonAutoPilotOptionsActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void jButtonBribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBribeActionPerformed
       if( nadeClient != null )
       {
          nadeClient.ShowBribeDialog();
       }
    }//GEN-LAST:event_jButtonBribeActionPerformed

    private void choiceGroupsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceGroupsItemStateChanged
       if( nadeClient != null )
       {
           nadeClient.UpdateGroups();
           GroupStatus gs = nadeClient.GetGroup( choiceGroups.getSelectedItem() );
           if( gs != null )
           {
              jTextFieldTheirMoney.setText(     String.valueOf( gs.getMoney())            );
              jTextFieldTheirResources.setText( String.valueOf( gs.getResources())        );
              jTextFieldTheirContracts.setText( String.valueOf( gs.getContractsWon())     );
              jTextFieldTheirHealth.setText(    String.valueOf( gs.getTrustWorthyLevel()) );
           }
       }
    }//GEN-LAST:event_choiceGroupsItemStateChanged

    private void jButtonChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChatActionPerformed
       if( nadeClient != null )
       {
           nadeClient.ShowChatDialog();
       }
    }//GEN-LAST:event_jButtonChatActionPerformed

    private void choiceGroupsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_choiceGroupsFocusGained
    }//GEN-LAST:event_choiceGroupsFocusGained

    private void jButtonInformationServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformationServerActionPerformed
       if( nadeClient != null )
       {
          nadeClient.ShowInformationServerGUI();
       }
    }//GEN-LAST:event_jButtonInformationServerActionPerformed

    private void jButtonRumourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRumourActionPerformed
       if( nadeClient != null )
       {
           nadeClient.ShowRumourDialog();
       }
    }//GEN-LAST:event_jButtonRumourActionPerformed

    private void jButtonSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecurityActionPerformed
       if( nadeClient != null )
       {
           nadeClient.ShowSecurityBreachDialog();
       }
    }//GEN-LAST:event_jButtonSecurityActionPerformed

    private void jCheckBoxAutoPilotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAutoPilotActionPerformed
       if( nadeClient != null )
       {
           nadeClient.EnableAutoPilot();
       }
    }//GEN-LAST:event_jCheckBoxAutoPilotActionPerformed

    private void jButtonBankingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBankingInfoActionPerformed
        if( nadeClient != null )
        {
           nadeClient.ShowBankingDialog();
        }
    }//GEN-LAST:event_jButtonBankingInfoActionPerformed

    private void jButtonTradeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTradeInfoActionPerformed
        if( nadeClient != null )
        {
           nadeClient.ShowTradingDialog();
        }
    }//GEN-LAST:event_jButtonTradeInfoActionPerformed

    private void jButtonHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHealthActionPerformed
       if( nadeClient != null )
       {
           nadeClient.RestoreHealth();
       }
    }//GEN-LAST:event_jButtonHealthActionPerformed

    private void jButtonShowContractInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowContractInfoActionPerformed
        if( nadeClient != null )
        {
           nadeClient.ShowContractInfoDialog();
        }
    }//GEN-LAST:event_jButtonShowContractInfoActionPerformed

    private void jButtonMakeBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeBidActionPerformed
      if( nadeClient != null )
      {
         nadeClient.MakeBid();
      }
    }//GEN-LAST:event_jButtonMakeBidActionPerformed

    private void jButtonMessageParserTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMessageParserTestActionPerformed
       
        if( nadeClient != null )
        {
           nadeClient.ShowMessageTest();
        }
        else
        {
            display( " Connect First. " );
        }
    }//GEN-LAST:event_jButtonMessageParserTestActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jEditorPaneLog.setText("<html></html>");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconnectActionPerformed
          try
          {
             nadeClient.stopClient();
          }
          catch( Exception e )
          {
             //jEditorPaneLog.append( e.getMessage() );
             display( "Exception: " + e.getMessage() );
          }
    }//GEN-LAST:event_jButtonDisconnectActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
       ConnectToNADE();
    }//GEN-LAST:event_jButtonConnectActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        try
        {
           java.awt.EventQueue.invokeLater( new Runnable()
           {
               public void run()
               {
                  NadeProjectGUIInterface nadeProjectGUIInterface = new NadeProjectGUIInterface();
                  nadeProjectGUIInterface.setVisible( true );
               }
           } );
        }
        catch( Exception e )
        {
            System.out.println( "Exception: " + e.getMessage() );
        }
    }


    /**Returns jEditorPaneLog*/
    javax.swing.JEditorPane getjEditorPaneLog()
    {
        return jEditorPaneLog;
    }
    /**Returns jFormattedTextFieldIPAddress*/
    javax.swing.JFormattedTextField getjFormattedTextFieldIPAddress()
    {
        return jFormattedTextFieldIPAddress;
    }
    /**Returns jFormattedTextFieldLocalIPAddress*/
    javax.swing.JFormattedTextField getjFormattedTextFieldLocalIPAddress()
    {
        return jFormattedTextFieldLocalIPAddress;
    }
    /**Returns jFormattedTextFieldPort*/
    public javax.swing.JFormattedTextField getjFormattedTextFieldPort()
    {
        return jFormattedTextFieldPort;
    }
    /**Returns jButtonDisconnect*/
    javax.swing.JButton getjButtonDisconnect()
    {
        return jButtonDisconnect;
    }
    /**Returns jButtonConnect*/
    javax.swing.JButton getjButtonConnect()
    {
        return jButtonConnect;
    }
    /**Returns jButtonMakeBid*/
    javax.swing.JButton getjButtonMakeBid()
    {
        return jButtonMakeBid;
    }
    /**Returns jButtonBribe*/
    javax.swing.JButton getjButtonBribe()
    {
        return jButtonBribe;
    }
    /**Returns jButtonHealth*/
    javax.swing.JButton getjButtonHealth()
    {
        return jButtonHealth;
    }
    /**Returns jButtonMessageParserTest*/
    javax.swing.JButton getjButtonMessageParserTest()
    {
        return jButtonMessageParserTest;
    }
    /**Returns jButtonShowContractInfo*/
    javax.swing.JButton getjButtonShowContractInfo()
    {
        return jButtonShowContractInfo;
    }
    /**Returns jButtonTradeInfo*/
    javax.swing.JButton getjButtonTradeInfo()
    {
        return jButtonTradeInfo;
    }
    /**Returns jButtonBankingInfo*/
    javax.swing.JButton getjButtonBankingInfo()
    {
        return jButtonBankingInfo;
    }
    /**Returns jButtonRumour*/
    javax.swing.JButton getjButtonRumour()
    {
        return jButtonRumour;
    }
    /**Returns jButtonSecurity*/
    javax.swing.JButton getjButtonSecurity()
    {
        return jButtonSecurity;
    }
    /**Returns jButtonInformationServer*/
    javax.swing.JButton getjButtonInformationServer()
    {
        return jButtonInformationServer;
    }
    /**Returns jButtonChat*/
    javax.swing.JButton getjButtonChat()
    {
        return jButtonChat;
    }
    /**Returns jButtonAutoPilotOptions*/
    javax.swing.JButton getjButtonAutoPilotOptions()
    {
        return jButtonAutoPilotOptions;
    }
    /**Returns jTextFieldTheirResources*/
    javax.swing.JTextField getjTextFieldTheirResources()
    {
       return jTextFieldTheirResources;
    }
    /**Returns jTextFieldTheirContracts*/
    javax.swing.JTextField getjTextFieldTheirContracts()
    {
       return jTextFieldTheirContracts;
    }
    /**Returns jTextFieldTheirHealth*/
    javax.swing.JTextField getjTextFieldTheirHealth()
    {
       return jTextFieldTheirHealth;
    }
    /**Returns jTextFieldTheirMoney*/
    javax.swing.JTextField getjTextFieldTheirMoney()
    {
       return jTextFieldTheirMoney;
    }
    /**Returns jTextFieldOurMoney*/
    javax.swing.JTextField getjTextFieldOurMoney()
    {
       return jTextFieldOurMoney;
    }
    /**Returns jTextFieldOurResources*/
    javax.swing.JTextField getjTextFieldOurResources()
    {
       return jTextFieldOurResources;
    }
    /**Returns jTextFieldOurContracts*/
    javax.swing.JTextField getjTextFieldOurContracts()
    {
       return jTextFieldOurContracts;
    }
    /**Returns jTextFieldOurHealth*/
    javax.swing.JTextField getjTextFieldOurHealth()
    {
       return jTextFieldOurHealth;
    }
    /**Returns jTextFieldBidAmount*/
    javax.swing.JTextField getjTextFieldBidAmount()
    {
       return jTextFieldBidAmount;
    }
    /**Returns jTextFieldRestoreHealth*/
    javax.swing.JTextField getjTextFieldRestoreHealth()
    {
        return jTextFieldRestoreHealth;
    }
    /**Returns jTextFieldControlResources*/
    javax.swing.JTextField getjTextFieldControlResources()
    {
        return jTextFieldControlResources;
    }
    /**Returns jTextFieldControlMoney*/
    javax.swing.JTextField getjTextFieldControlMoney()
    {
        return jTextFieldControlMoney;
    }
    /**Returns jTextFieldGameLength*/
    javax.swing.JTextField getjTextFieldGameLength()
    {
        return jTextFieldGameLength;
    }
    /**Returns choiceGroups*/
    java.awt.Choice getchoiceGroups()
    {
        return choiceGroups;
    }
    /**Returns jCheckBoxAutoPilot*/
    javax.swing.JCheckBox getjCheckBoxAutoPilot()
    {
        return jCheckBoxAutoPilot;
    }
    /**Returns jCheckBoxInformationServerRunning*/
    javax.swing.JCheckBox getjCheckBoxInformationServerRunning()
    {
        return jCheckBoxInformationServerRunning;
    }
    /**Returns jTextFieldPublicName*/
    javax.swing.JTextField getjTextFieldPublicName()
    {
        return jTextFieldPublicName;
    }
    /**Returns jTextFieldTheirIPAddress*/
    javax.swing.JTextField getjTextFieldTheirIPAddress()
    {
        return jTextFieldTheirIPAddress;
    }
    /**Returns jCheckBoxBlock*/
    javax.swing.JCheckBox getjCheckBoxBlock()
    {
        return jCheckBoxBlock;
    }
    /**@returns jButtonStandings*/
    javax.swing.JButton getjButtonStandings()
    {
       return jButtonStandings;
    }
    /**@return jTextFieldAdditionalBidAmount*/
    javax.swing.JTextField getjTextFieldAdditionalBidAmount()
    {
        return jTextFieldAdditionalBidAmount;
    }
    /**@return jCheckBoxConnectedToDatabase*/
    javax.swing.JCheckBox getjCheckBoxConnectedToDatabase()
    {
       return jCheckBoxConnectedToDatabase;
    }
    /**@return jSliderAdditionalBidAmount*/
    javax.swing.JSlider getjSliderAdditionalBidAmount()
    {
       return jSliderAdditionalBidAmount;
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceGroups;
    private javax.swing.JButton jButtonAutoPilotOptions;
    private javax.swing.JButton jButtonBankingInfo;
    private javax.swing.JButton jButtonBribe;
    private javax.swing.JButton jButtonChat;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonHealth;
    private javax.swing.JButton jButtonInformationServer;
    private javax.swing.JButton jButtonMakeBid;
    private javax.swing.JButton jButtonMessageParserTest;
    private javax.swing.JButton jButtonRumour;
    private javax.swing.JButton jButtonSecurity;
    private javax.swing.JButton jButtonShowContractInfo;
    private javax.swing.JButton jButtonStandings;
    private javax.swing.JButton jButtonStartNade;
    private javax.swing.JButton jButtonTradeInfo;
    private javax.swing.JCheckBox jCheckBoxAutoPilot;
    private javax.swing.JCheckBox jCheckBoxBlock;
    private javax.swing.JCheckBox jCheckBoxConnectedToDatabase;
    private javax.swing.JCheckBox jCheckBoxInformationServerRunning;
    private javax.swing.JEditorPane jEditorPaneLog;
    private javax.swing.JFormattedTextField jFormattedTextFieldIPAddress;
    private javax.swing.JFormattedTextField jFormattedTextFieldLocalIPAddress;
    private javax.swing.JFormattedTextField jFormattedTextFieldPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBidAmount;
    private javax.swing.JLabel jLabelControlMoney;
    private javax.swing.JLabel jLabelGameLength;
    private javax.swing.JLabel jLabelGroup;
    private javax.swing.JLabel jLabelIPAddress;
    private javax.swing.JLabel jLabelLocalIPAddress;
    private javax.swing.JLabel jLabelNadeServerIPAddress;
    private javax.swing.JLabel jLabelOurContracts;
    private javax.swing.JLabel jLabelOurHealth;
    private javax.swing.JLabel jLabelOurMoney;
    private javax.swing.JLabel jLabelOurResources;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelPublicName;
    private javax.swing.JLabel jLabelRestoreHealth;
    private javax.swing.JLabel jLabelTheirContracts;
    private javax.swing.JLabel jLabelTheirHealth;
    private javax.swing.JLabel jLabelTheirResources;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelShowMessageParserTest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderAdditionalBidAmount;
    private javax.swing.JTextField jTextFieldAdditionalBidAmount;
    private javax.swing.JTextField jTextFieldBidAmount;
    private javax.swing.JTextField jTextFieldControlMoney;
    private javax.swing.JTextField jTextFieldControlResources;
    private javax.swing.JTextField jTextFieldGameLength;
    private javax.swing.JTextField jTextFieldOurContracts;
    private javax.swing.JTextField jTextFieldOurHealth;
    private javax.swing.JTextField jTextFieldOurMoney;
    private javax.swing.JTextField jTextFieldOurResources;
    private javax.swing.JTextField jTextFieldPublicName;
    private javax.swing.JTextField jTextFieldRestoreHealth;
    private javax.swing.JTextField jTextFieldTheirContracts;
    private javax.swing.JTextField jTextFieldTheirHealth;
    private javax.swing.JTextField jTextFieldTheirIPAddress;
    private javax.swing.JTextField jTextFieldTheirMoney;
    private javax.swing.JTextField jTextFieldTheirResources;
    // End of variables declaration//GEN-END:variables
    
}
