/*
 * StandingsDialog.java
 *
 * Created on March 16, 2007, 1:22 AM
 */

package nade_project;

import java.util.*;
import javax.swing.*;

/**
 *This dialog allows the user who is in 1st place second place ect...
 * @author  Default
 */
public class StandingsDialog extends javax.swing.JFrame {

    /**Nade Client class*/
    NadeClient nadeClient;

    /** Creates new form StandingsDialog */
    public StandingsDialog( NadeClient _nadeClient )
    {
       initComponents();
       nadeClient = _nadeClient;
    }

    /**Sorts the clients according to their profit*/
    public synchronized void UpdateStandings()
    {
        if( nadeClient != null )
        {
           try
           {
              jListGroups.removeAll();
              ArrayList<GroupStatus> groupStatusList = new ArrayList<GroupStatus>( nadeClient.groupStatusList );
              GroupStatus gs;
              groupStatusList.add( nadeClient.ourGroupStatus );
              // Sort the list in decending order.
              // First - Last
              Collections.sort( groupStatusList );
              DefaultListModel listModel = new DefaultListModel();
              for( int i=0 ; i<groupStatusList.size() ; i++ )
              {
                 gs = groupStatusList.get( i );
                 listModel.addElement( String.valueOf( i+1 ) + " : " + gs.getName() + " with " + String.valueOf( gs.getMoney() ) + " profit." );
              }
              // Update list contents.
              jListGroups.setModel( listModel );

              try
              {
                  // This causes the program to crash. I dont know why.
                 //int contractsleft = 90 - nadeClient.contract.getNumber();
                 //jTextFieldContractsLeft.setText( String.valueOf( contractsleft ) );
              }
              catch( Exception e )
              {
              }              
           }
           catch( Exception e )
           {
              nadeClient.display( "StandingsDialog.UpdateStandings - Exception: " + e.getMessage() );
           }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelDescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelContractsLeft = new javax.swing.JLabel();
        jTextFieldContractsLeft = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGroups = new javax.swing.JList();

        setTitle("Standings Dialog");
        jLabelDescription.setText("Sorted by order of estimated profit.");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelContractsLeft.setText("Contracts Left");

        jTextFieldContractsLeft.setDocument(new IntegerDocument());
        jTextFieldContractsLeft.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelContractsLeft)
                .addGap(14, 14, 14)
                .addComponent(jTextFieldContractsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContractsLeft)
                    .addComponent(jTextFieldContractsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jListGroups);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescription))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**@return jListGroups*/
    javax.swing.JList getjListGroups()
    {
       return jListGroups;
    }

    /**@return jTextFieldContractsLeft*/
    public javax.swing.JTextField getjTextFieldContractsLeft()
    {
       return jTextFieldContractsLeft;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelContractsLeft;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JList jListGroups;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldContractsLeft;
    // End of variables declaration//GEN-END:variables
    
}
